#!/usr/bin/env bash
# Kiaros Linux installer
# Installs the systemd user service, .desktop launcher, and XDG directories.
# Run from the project root: bash install.sh
# Re-run after git pull to update the service definition.

set -euo pipefail

KIAROS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NODE_BIN="$(which node 2>/dev/null || echo '')"

# ── Sanity checks ─────────────────────────────────────────────────────────
if [[ -z "$NODE_BIN" ]]; then
  echo "Error: node not found on \$PATH. Install Node.js ≥ 18 first." >&2
  exit 1
fi

NODE_VERSION="$("$NODE_BIN" -e 'process.stdout.write(process.version)')"
NODE_MAJOR="${NODE_VERSION//v/}"
NODE_MAJOR="${NODE_MAJOR%%.*}"
if (( NODE_MAJOR < 18 )); then
  echo "Error: Node.js ≥ 18 required (found $NODE_VERSION)." >&2
  exit 1
fi

# ── XDG directories ───────────────────────────────────────────────────────
CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}"

KIAROS_CONFIG_DIR="${CONFIG_HOME}/kiaros"
KIAROS_DATA_DIR="${DATA_HOME}/kiaros"
KIAROS_CACHE_DIR="${CACHE_HOME}/kiaros"

mkdir -p \
  "${KIAROS_CONFIG_DIR}" \
  "${KIAROS_DATA_DIR}/generated" \
  "${KIAROS_DATA_DIR}/notes" \
  "${KIAROS_CACHE_DIR}"

echo "Config dir : ${KIAROS_CONFIG_DIR}"
echo "Data dir   : ${KIAROS_DATA_DIR}"

# ── Migrate legacy data (if present) ─────────────────────────────────────
LEGACY_DB="${KIAROS_DIR}/kiaros.db"
LEGACY_CONFIG="${KIAROS_DIR}/kiaros.config.json"

if [[ -f "$LEGACY_DB" && ! -f "${KIAROS_DATA_DIR}/kiaros.db" ]]; then
  echo "Migrating legacy database → ${KIAROS_DATA_DIR}/kiaros.db"
  cp "$LEGACY_DB" "${KIAROS_DATA_DIR}/kiaros.db"
  mv "$LEGACY_DB" "${LEGACY_DB}.migrated"
fi

if [[ -f "$LEGACY_CONFIG" && ! -f "${KIAROS_CONFIG_DIR}/config.json" ]]; then
  echo "Migrating legacy config   → ${KIAROS_CONFIG_DIR}/config.json"
  cp "$LEGACY_CONFIG" "${KIAROS_CONFIG_DIR}/config.json"
  mv "$LEGACY_CONFIG" "${LEGACY_CONFIG}.migrated"
fi

# ── Wrapper script ────────────────────────────────────────────────────────
# A stable entry-point at ~/.local/bin/kiaros so the service unit doesn't
# need to be re-stamped every time Node moves.
BIN_DIR="${HOME}/.local/bin"
mkdir -p "$BIN_DIR"

WRAPPER="${BIN_DIR}/kiaros"
cat > "$WRAPPER" <<EOF
#!/bin/sh
# Kiaros launcher — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
exec "$NODE_BIN" "${KIAROS_DIR}/server/index.js" "\$@"
EOF
chmod +x "$WRAPPER"
echo "Wrapper    : ${WRAPPER}"

# ── systemd user service ──────────────────────────────────────────────────
SYSTEMD_DIR="${CONFIG_HOME}/systemd/user"
mkdir -p "$SYSTEMD_DIR"

SERVICE_SRC="${KIAROS_DIR}/systemd/kiaros.service"
SERVICE_DST="${SYSTEMD_DIR}/kiaros.service"

sed "s|%%KIAROS_EXEC%%|${WRAPPER}|g" "$SERVICE_SRC" > "$SERVICE_DST"

systemctl --user daemon-reload
systemctl --user enable kiaros.service
echo "Service    : ${SERVICE_DST} (enabled)"

# ── .desktop launcher ─────────────────────────────────────────────────────
APPS_DIR="${DATA_HOME}/applications"
mkdir -p "$APPS_DIR"
cp "${KIAROS_DIR}/assets/kiaros.desktop" "${APPS_DIR}/kiaros.desktop"
update-desktop-database "$APPS_DIR" 2>/dev/null && echo "Desktop    : ${APPS_DIR}/kiaros.desktop" || true

# ── Done ──────────────────────────────────────────────────────────────────
echo ""
echo "Kiaros installed successfully."
echo ""
echo "  Start :  systemctl --user start kiaros"
echo "  Stop  :  systemctl --user stop kiaros"
echo "  Logs  :  journalctl --user -u kiaros -f"
echo "  Open  :  xdg-open http://localhost:3333"
echo ""
echo "To start now: systemctl --user start kiaros"
